### ISSUE TITLE
CSS Style

### ISSUE THREAD

**Issue by jim-rosales** [shirleyxx100/prj-rev-bwfs-dasmoto#4]
Excellent job applying your CSS styles efficiently! One thing to note is that its convention to add a space before the opening bracket `{`

You have:
```CSS
body {
  font-family: Helvetica;
}
```

Should be:
```CSS
body {
  font-family: Helvetica;
}
```

https://github.com/shirleyxx100/prj-rev-bwfs-dasmoto/blob/827d48ba766472ca42808542fcc72a2589597f32/Dasmotos_Arts_and_Crafts/resources/css/style.css#L1-L14
